model:
  base_learning_rate: 3e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ckpt_path: /nfs/lhan/active/taming-transformers/logs/2021-09-18T03-32-01_custom_vqgan_vb100_frame_128/checkpoints/last.ckpt
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 1
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 48
    num_workers: 16
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /nfs/lhan/data/DALLE/multi-bird/cub200+vb100_train.txt
        size: 128
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /nfs/lhan/data/DALLE/multi-bird/cub200+vb100_val.txt
        size: 128

