model:
  base_learning_rate: 3e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ckpt_path: logs/2022-01-24T21-39-05_custom_vqgan_kinetics-6_128_mp4/checkpoints/last.ckpt
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: taming.data.custom.CustomVideoTrain
      params:
        training_images_list_file: /dresden/users/lh599/Data/kinetics-dataset/six_god_list_train2.txt
        size: 128
    validation:
      target: taming.data.custom.CustomVideoTest
      params:
        test_images_list_file: /dresden/users/lh599/Data/kinetics-dataset/six_god_list_val2.txt
        size: 128

